---
name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Test building image.
        run: docker build -t rockylinux9 .

      - name: Run the built image.
        run: >-
          docker run --name test-container -d --privileged
          -v /sys/fs/cgroup:/sys/fs/cgroup:rw --cgroupns=host
          rockylinux9

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-container env TERM=xterm ansible --version

  # If on main branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rockylinux9:latest
